---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: vault
  namespace: vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1h
  chart:
    spec:
      chart: vault
      version: "0.30.x"
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
  values:
    # Base values
    global:
      openshift: false
    injector:
      enabled: false