---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-helm-max-history
  annotations:
    policies.kyverno.io/severity: low
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: set-helm-max-history
      match:
        any:
          - resources:
              kinds: [HelmRelease]
              namespaces: ["*"]
      mutate:
        patchStrategicMerge:
          spec:
            +(maxHistory): 3
