---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: set-revision-history-limit
  annotations:
    policies.kyverno.io/severity: low
spec:
  rules:
    - name: set-revision-history-limit
      match:
        any:
          - resources:
              kinds: [Deployment, StatefulSet, DaemonSet]
      mutate:
        patchStrategicMerge:
          spec:
            revisionHistoryLimit: 3
