---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nextcloud 
  namespace: nextcloud 
spec:
  interval: 24h
  url: https://nextcloud.github.io/helm/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud 
  namespace: nextcloud 
spec:
  interval: 1h
  chart:
    spec:
      chart: nextcloud
      version: "6.6.x"
      sourceRef:
        kind: HelmRepository
        name: nextcloud 
        namespace: nextcloud 