---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: nextcloud 
  namespace: nextcloud 
spec:
  interval: 12h
  timeout: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  # verify:
  #   provider: cosign
  ref:
    semver: "7.x.x"
  url: oci://ghcr.io/nextcloud/helm/nextcloud
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud 
  namespace: nextcloud 
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: nextcloud
    namespace: nextcloud