---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    semver: ">=0.38.0 <1.00.0"
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-metrics-k8s-stack
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-metrics-k8s-stack
    namespace: monitoring
  values:
    vmsingle:
      spec:
        retentionPeriod: "2" # in months
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault
        storage:
          storageClassName: "default"
          resources:
            requests:
              storage: 50Gi

    vmagent:
      spec:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault

    vmalert:
      spec:
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
          seccompProfile:
            type: RuntimeDefault

    grafana:
      persistence:
        enabled: true
        storageClassName: "default"
        size: 5Gi
      securityContext:
        seccompProfile:
          type: RuntimeDefault
