---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  interval: 24h
  dependsOn:
    - name: mariadb-operator-crds
      namespace: mariadb-operator
  chart:
    spec:
      chart: mariadb-operator
      version: ">=25.8.0 <30.0.0"
      sourceRef:
        kind: HelmRepository
        name: mariadb-operator
        namespace: mariadb-operator
  values:
    metrics:
      enabled: false
    webhook:
      enabled: true