---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  # Merge development-specific configuration
  - path: config.yaml
    target:
      kind: HelmRelease
      name: authentik
      namespace: authentik
  