---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-operator
  namespace: tekton-operator
spec:
  interval: 24h
  url: https://github.com/tektoncd/operator
  ref:
    branch: "release-v0.76.x"
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-operator
  namespace: tekton-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/tekton-operator
      version: "0.76.x"
      sourceRef:
        kind: GitRepository
        name: tekton-operator
        namespace: tekton-operator
