---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tekton-operator
  namespace: tekton-operator
spec:
  interval: 24h
  url: https://github.com/tektoncd/operator
  ref:
    # semver uses tag
    semver: ">=0.77.0 <1.0.0"
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tekton-operator
  namespace: tekton-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: charts/tekton-operator
      sourceRef:
        kind: GitRepository
        name: tekton-operator
        namespace: tekton-operator
