---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  # Merge development-specific configuration
  - path: config.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
      namespace: weave-gitops
  
  # # Patch ingress for dev environment
  # - patch: |
  #     - op: replace
  #       path: /spec/rules/0/host
  #       value: gitops.dev-cluster.local
  #   target:
  #     kind: Ingress
  #     name: weave-gitops-cilium
  #     namespace: weave-gitops