---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  values:
    nextcloud:
      host: nextcloud.example.com
      username: admin
      password: changeme
      containerPort: 80
      datadir: /var/www/html/data

      podSecurityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
        runAsNonRoot: true

    internalDatabase:
      enabled: true

    resources:
      limits:
        memory: 4096Mi
      requests:
        cpu: 500m
        memory: 2048Mi