---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "nginx-pool"
spec:
  blocks:
    - start: "192.168.35.79"
      stop: "192.168.35.79"
  serviceSelector:
    matchLabels:
      ciliuml2: nginx
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-pool"
spec:
  blocks:
    - start: "192.168.35.70"
      stop: "192.168.35.70"
  serviceSelector:
    matchLabels:
      ciliuml2: cilium
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "general-pool"
spec:
  blocks:
    - start: "192.168.35.90"
      stop: "192.168.35.100"
  serviceSelector:
    matchLabels:
      ciliuml2: pool
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: cilium-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
    - ^eth[0-9]+ # Matches interfaces like eth0, eth1, etc.
    - ^enp[0-9]+s[0-9]+ # Matches interfaces like enp3s0, enp4s1, etc.
    - ^ens[0-9]+ # Matches interfaces like ens3, ens4, etc.
    - ^eno[0-9]+ # Matches interfaces like eno1, eno2, etc.
    - ^enx[0-9a-fA-F]+ # Matches interfaces like enx001122334455
    - ^wlan[0-9]+ # Matches interfaces like wlan0, wlan1, etc.
  # - ^veth[0-9a-zA-Z]+   # Matches virtual ethernet interfaces like veth0, veth1, etc.
  serviceSelector:
    matchLabels:
      ciliuml2: cilium
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: nginx-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
    - ^eth[0-9]+ # Matches interfaces like eth0, eth1, etc.
    - ^enp[0-9]+s[0-9]+ # Matches interfaces like enp3s0, enp4s1, etc.
    - ^ens[0-9]+ # Matches interfaces like ens3, ens4, etc.
    - ^eno[0-9]+ # Matches interfaces like eno1, eno2, etc.
    - ^enx[0-9a-fA-F]+ # Matches interfaces like enx001122334455
    - ^wlan[0-9]+ # Matches interfaces like wlan0, wlan1, etc.
  # - ^veth[0-9a-zA-Z]+   # Matches virtual ethernet interfaces like veth0, veth1, etc.
  serviceSelector:
    matchLabels:
      ciliuml2: nginx
---
apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: pool-policy
spec:
  externalIPs: true
  loadBalancerIPs: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
    - ^eth[0-9]+ # Matches interfaces like eth0, eth1, etc.
    - ^enp[0-9]+s[0-9]+ # Matches interfaces like enp3s0, enp4s1, etc.
    - ^ens[0-9]+ # Matches interfaces like ens3, ens4, etc.
    - ^eno[0-9]+ # Matches interfaces like eno1, eno2, etc.
    - ^enx[0-9a-fA-F]+ # Matches interfaces like enx001122334455
    - ^wlan[0-9]+ # Matches interfaces like wlan0, wlan1, etc.
  # - ^veth[0-9a-zA-Z]+   # Matches virtual ethernet interfaces like veth0, veth1, etc.
  serviceSelector:
    matchLabels:
      ciliuml2: pool