---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway-internal
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    #annotations:
    #  ingress.cilium.io/loadbalancer-mode: dedicated
    labels:
      lb.cilium.io/pool: envoy-gateway-internal
  listeners:
    - name: http
      protocol: HTTP
      #hostname: "*.tokamak.labza"
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      #hostname: "*.tokamak.labza"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            namespace: envoy-gateway-system
            name: envoy-gateway-internal-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway-internal-cert
  namespace: envoy-gateway-system
spec:
  dnsNames:
    - "*.tokamak.labza"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: labza-ca
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
    size: 256
  secretName: envoy-gateway-internal-cert
  usages:
    - digital signature
    - key encipherment
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway-external
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    #annotations:
    #  ingress.cilium.io/loadbalancer-mode: dedicated
    labels:
      lb.cilium.io/pool: envoy-gateway-external
  listeners:
    - name: http
      protocol: HTTP
      #hostname: "*.tokamak.labza"
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      #hostname: "*.tokamak.labza"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            namespace: envoy-gateway-system
            name: envoy-gateway-external-cert
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: zapf.marcel@outlook.com
    privateKeySecretRef:
      name: letsencrypt-prod-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - kind: Gateway
            name: envoy-gateway-external
            namespace: envoy-gateway-system
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway-external-cert
  namespace: envoy-gateway-system
spec:
  secretName: envoy-gateway-external-cert
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS8
    size: 256
  commonName: "*.menofgaming.de"
  dnsNames:
    - "*.menofgaming.de" 