---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway-internal
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    annotations:
      ingress.cilium.io/loadbalancer-mode: dedicated
    labels:
      lb.cilium.io/pool: cilium
  listeners:
    - name: http
      protocol: HTTP
      #hostname: "*.tokamak.labza"
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      #hostname: "*.tokamak.labza"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            namespace: envoy-gateway-system
            name: envoy-gateway-internal-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway-internal-cert
  namespace: envoy-gateway-system
spec:
  dnsNames:
    - "*.tokamak.labza"
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: labza-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: envoy-gateway-internal-cert
  usages:
    - digital signature
    - key encipherment
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway-external
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy-gateway
  infrastructure:
    annotations:
      ingress.cilium.io/loadbalancer-mode: dedicated
    labels:
      lb.cilium.io/pool: nginx
  listeners:
    - name: http
      protocol: HTTP
      #hostname: "*.tokamak.labza"
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: https
      protocol: HTTPS
      #hostname: "*.tokamak.labza"
      port: 443
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            namespace: envoy-gateway-system
            name: envoy-gateway-internal-cert