{
 "title": "Talos Cluster Hardware Monitoring",
 "tags": [
  "hardware",
  "talos",
  "cpu",
  "gpu"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cpu_chip", "label": "CPU hwmon chip", "query": "pci0000:00_0000:00:18_3" },
   { "name": "gpu_chip", "label": "GPU hwmon chip", "query": "0000:00:08_1_0000:05:00_0" },
   { "name": "nvme_chip_pattern", "label": "NVMe hwmon chip regex", "query": "nvme_nvme.*" },
   { "name": "nvme_sensor", "label": "NVMe temp sensor", "query": "temp1" }
  ]
 },
 "panels": [
  {
   "title": "CPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_hwmon_temp_celsius{chip=\"$cpu_chip\"},\r\n  \"internal_ip\",\r\n  \"$1\",\r\n  \"instance\",\r\n  \"([^:]+):.*\"\r\n)\r\n* on(internal_ip) group_left(node)\r\nkube_node_info",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "NVMe Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  label_replace(\r\n    node_hwmon_temp_celsius{chip=~\"$nvme_chip_pattern\", sensor=\"$nvme_sensor\"},\r\n    \"internal_ip\",\r\n    \"$1\",\r\n    \"instance\",\r\n    \"([^:]+):.*\"\r\n  ),\r\n  \"device\",\r\n  \"nvme$1\",\r\n  \"chip\",\r\n  \"nvme_nvme(.*)\"\r\n)\r\n* on(internal_ip) group_left(node)\r\nkube_node_info\r\n* on(instance, device) group_left(model)\r\nnode_nvme_info",
     "legendFormat": " {{node}}-{{model}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_hwmon_temp_celsius{chip=\"$gpu_chip\"},\r\n  \"internal_ip\",\r\n  \"$1\",\r\n  \"instance\",\r\n  \"([^:]+):.*\"\r\n)\r\n* on(internal_ip) group_left(node)\r\nkube_node_info",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_hwmon_temp_celsius{chip=\"$cpu_chip\"},\r\n  \"internal_ip\",\r\n  \"$1\",\r\n  \"instance\",\r\n  \"([^:]+):.*\"\r\n)\r\n* on(internal_ip) group_left(node)\r\nkube_node_info",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "°C" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_hwmon_temp_celsius{chip=\"$gpu_chip\"},\r\n  \"internal_ip\",\r\n  \"$1\",\r\n  \"instance\",\r\n  \"([^:]+):.*\"\r\n)\r\n* on(internal_ip) group_left(node)\r\nkube_node_info",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Package Power",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_hwmon_power_watt{chip=\"$gpu_chip\"},\r\n  \"internal_ip\",\r\n  \"$1\",\r\n  \"instance\",\r\n  \"([^:]+):.*\"\r\n)\r\n* on(internal_ip) group_left(node)\r\nkube_node_info",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Cluster Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "sum (node_hwmon_power_watt{chip=\"$gpu_chip\"})",
     "legendFormat": "Power"
    },
    {
     "expr": "avg_over_time((sum(node_hwmon_power_watt{chip=\"$gpu_chip\"}))[$__range:5m] @ end())",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Cluster Power Consumption",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (node_hwmon_power_watt{chip=\"$gpu_chip\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVMe Information",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "label_replace(\r\n  node_nvme_info,\r\n  \"internal_ip\",\r\n  \"$1\",\r\n  \"instance\",\r\n  \"([^:]+):.*\"\r\n)\r\n* on(internal_ip) group_left(node)\r\nkube_node_info",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}