---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-prod
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-prod
  namespace: mariadb-prod
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: true

  storage:
    size: 10Gi
    storageClassName: longhorn-prod

  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 999
    runAsGroup: 999
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

  service:
    type: LoadBalancer
    metadata:
      labels:
        lb.cilium.io/pool: general
---
#
# ADA --------------------------
#
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: ada
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  characterSet: utf8
  collate: utf8_general_ci
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: mzapf
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  passwordSecretKeyRef:
    name: user-mzapf
    key: password
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    # - "ALL PRIVILEGES"
  database: "*"
  table: "*"
  username: mzapf
  grantOption: true
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
#
# forgejo --------------------------
#
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: forgejo
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  characterSet: utf8mb4
  collate: utf8mb4_0900_as_cs
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: forgejo
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  passwordSecretKeyRef:
    name: user-forgejo
    key: password
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: forgejo
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  privileges:
    - "ALL PRIVILEGES"
  database: "forgejo"
  table: "*"
  username: forgejo
  grantOption: true
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
#
# forgejo --------------------------
#
apiVersion: k8s.mariadb.com/v1alpha1
kind: Database
metadata:
  name: nextcloud
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  characterSet: utf8mb4
  collate: utf8mb4_general_ci
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: User
metadata:
  name: nextcloud
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  passwordSecretKeyRef:
    name: user-nextcloud
    key: password
  maxUserConnections: 20
  host: "%"
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: nextcloud
  namespace: mariadb-prod
spec:
  mariaDbRef:
    name: mariadb-prod
  privileges:
    - "ALL PRIVILEGES"
  database: "nextcloud"
  table: "*"
  username: nextcloud
  grantOption: true
  host: "%"
  # Delete the resource in the database whenever the CR gets deleted.
  # Alternatively, you can specify Skip in order to omit deletion.
  cleanupPolicy: Delete
  requeueInterval: 10h
  retryInterval: 30s