---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-prod
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-prod
  namespace: mariadb-prod
spec:

  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: true

  storage:
    size: 10Gi
    storageClassName: longhorn-prod
