---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb-galera-prod
---
apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb-galera-prod
  namespace: mariadb-galera-prod
spec:

  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password
    generate: true

  storage:
    size: 10Gi
    storageClassName: longhorn-prod

  replicas: 3

  galera:
    enabled: true
    config:
      reuseStorageVolume: true