---
apiVersion: v1
kind: Namespace
metadata:
  name: renovate
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
  namespace: renovate
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
          containers:
            - image: ghcr.io/renovatebot/renovate:43.29
              name: renovate-bot
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: RENOVATE_CONFIG_FILE
                  value: /opt/renovate/config.json
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
                - name: config-volume
                  mountPath: /opt/renovate/config.json
                  subPath: config.json
                  readOnly: true
                - name: work-volume
                  mountPath: /tmp/renovate/
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
          restartPolicy: Never
          volumes:
            - name: config-volume
              configMap:
                name: renovate-config
            - name: work-volume
              emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
  namespace: renovate
data:
  config.json: |-
    {
      "repositories": ["Syntax3rror404/infra"],
      "extends": ["config:recommended"],
      "dependencyDashboard": true
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: renovate-env
  namespace: renovate
type: Opaque
stringData:
  RENOVATE_PLATFORM: "${renovate_plattform}"
  RENOVATE_GIT_AUTHOR: "${renovate_git_author}"
  RENOVATE_TOKEN: "${renovate_token}"
  RENOVATE_AUTODISCOVER: "${renovate_autodiscover}"