apiVersion: batch/v1
kind: CronJob
metadata:
  name: talos-etcd-defrag
  namespace: kube-system
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
  labels:
    app.kubernetes.io/name: talos-etcd-defrag
    app.kubernetes.io/component: etcd-maintenance
    app.kubernetes.io/part-of: talos
spec:
  schedule: "0 4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: talos-etcd-defrag
            app.kubernetes.io/component: etcd-maintenance
            app.kubernetes.io/part-of: talos
        spec:
          restartPolicy: OnFailure
          nodeSelector:
            node-role.kubernetes.io/control-plane: ""
          tolerations:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
              effect: NoSchedule
          containers:
            - name: etcd-defrag
              image: docker.io/library/alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659
              env:
                - name: ETCD_IPS
                  value: "tokamak-m1 tokamak-m2 tokamak-m3"

                - name: TALOSCTL_VERSION
                  value: "v1.12.4"

                - name: WAIT_TIME
                  value: "10"

              command:
                - sh
                - -c
                - |
                  set -euo pipefail

                  echo "================================================"
                  echo "Using ETCD IPs:"
                  echo "${ETCD_IPS}"
                  echo ""
                  echo "Using talosctl version: ${TALOSCTL_VERSION}"
                  echo "================================================"
                  echo ""

                  echo "Installing dependencies..."
                  apk update
                  apk add --no-cache wget
                  
                  echo "Downloading talosctl ${TALOSCTL_VERSION}..."
                  wget https://github.com/siderolabs/talos/releases/download/${TALOSCTL_VERSION}/talosctl-linux-amd64 -O /usr/local/bin/talosctl
                  chmod +x /usr/local/bin/talosctl

                  echo ""
                  echo "================================================"
                  echo "Starting etcd defragmentation and waiting ${WAIT_TIME} seconds between nodes..."
                  echo "================================================"
                  echo ""

                  count=0
                  total=$(echo "${ETCD_IPS}" | wc -w)

                  for ip in ${ETCD_IPS}; do
                    count=$((count + 1))

                    echo "================================================"
                    echo "Defragmenting etcd on node ${ip}..."
                    echo "================================================"

                    echo ""
                    echo "Initial etcd status before defragmentation:"
                    talosctl --nodes ${ip} etcd status
                    echo ""

                    if talosctl --nodes ${ip} etcd defrag; then
                      echo ""
                      echo "Successfully defragmented etcd on ${ip}"
                    else
                      echo ""
                      echo "Failed to defragment etcd on ${ip}"
                      echo "Failed etcd status:"
                      talosctl --nodes ${ip} etcd status
                      exit 1
                    fi

                    echo ""
                    echo "Final etcd status after defragmentation:"
                    talosctl --nodes ${ip} etcd status
                    echo ""

                    if [ "${count}" -lt "${total}" ]; then
                      echo "Waiting ${WAIT_TIME} seconds before next node..."
                      for i in $(seq ${WAIT_TIME} -1 1); do
                        echo "Countdown: ${i} seconds remaining..."
                        sleep 1
                      done
                      echo "Wait completed - proceeding to next node"
                      echo ""
                    fi
                  done

                  echo "================================================"
                  echo "etcd defragmentation completed for all etcd nodes!"
                  echo "================================================"
              securityContext:
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
              volumeMounts:
                - mountPath: /var/run/secrets/talos.dev
                  name: talos-etcd-defrag-secret
                  readOnly: true
          volumes:
            - name: talos-etcd-defrag-secret
              secret:
                secretName: talos-etcd-defrag-secret
---
# Creates talos-etcd-defrag-secret inside kube-system namespace with talosconfig
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: talos-etcd-defrag-secret
  namespace: kube-system
spec:
  roles:
    - os:operator