---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-operator
spec:
  interval: ${helm_source_interval}
  timeout: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  #verify:
  #  provider: cosign
  ref:
    semver: ">=26.0.0 <30.0.0"
  url: oci://ghcr.io/mariadb-operator/charts/mariadb-operator-crds
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator-crds
  namespace: mariadb-operator
spec:
  interval: ${helm_release_interval}
  maxHistory: 3
  chartRef:
    kind: OCIRepository
    name: mariadb-operator-crds
    namespace: mariadb-operator
