---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 24h
  timeout: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  #verify:
  #  provider: cosign
  ref:
    semver: ">=1.18.6 <1.20.0"
  url: oci://quay.io/cilium/charts/cilium
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cilium
    namespace: kube-system
  values:
    bpf:
      masquerade: true
      datapathMode: netkit
      distributedLRU:
        enabled: true
      mapDynamicSizeRatio: 0.004
    bpfClockProbe: true
    # fix for masquerade under talos
    socketLB:
      enabled: true
      hostNamespaceOnly: true
    bandwidthManager:
      enabled: true
    autoDirectNodeRoutes: true
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    externalIPs:
      enabled: true
    operator:
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/control-plane: ""
    hubble:
      relay:
        enabled: true
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        nodeSelector:
          kubernetes.io/os: linux
          node-role.kubernetes.io/control-plane: ""
      ui:
        enabled: true
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        nodeSelector:
          kubernetes.io/os: linux
          node-role.kubernetes.io/control-plane: ""
    ingressController:
      enabled: false
      service:
        labels:
          lb.cilium.io/pool: cilium
    ipam:
      mode: kubernetes
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    k8sServiceHost: localhost
    k8sServicePort: 7445
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
      leaseDuration: 120s
      leaseRenewDeadline: 60s
      leaseRetryPeriod: 1s
    loadBalancer:
      mode: hybrid
      # XDP could, needs driver support
      # acceleration: native
    routingMode: native
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    # replaced by envoy-gateway
    gatewayAPI:
      enabled: false
    envoy:
      enabled: false
