---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: ${helm_source_interval}
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: ${helm_release_interval}
  maxHistory: 3
  chart:
    spec:
      chart: longhorn
      version: "1.12.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
