---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 24h
  url: https://cloudflare.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.x"
      sourceRef:
        kind: HelmRepository
        name: cloudflared
        namespace: cloudflared