---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  values:
    server:
      controller:
        allowSnippetAnnotations: true
        config:
          annotations-risk-level: Critical
