---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: changeme
        accessMode: ReadWriteOnce
