---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  # Merge development-specific configuration
  - path: config.yaml
    target:
      kind: HelmRelease
      name: oauth2-proxy
      namespace: oauth2-proxy
  
  # # Patch ingress for dev environment
  # - patch: |
  #     - op: replace
  #       path: /spec/rules/0/host
  #       value: oauth2-proxy.dev-cluster.local
  #   target:
  #     kind: Ingress
  #     name: oauth2-proxy-cilium
  #     namespace: oauth2-proxy