---
# Include flux/infrastructure as cluster-infrastructure
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-infrastructure
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: flux/infrastructure
  prune: true
  wait: true
  timeout: 10m0s
  retryInterval: 1m0s
---
# Include flux/clusters/clustername/apps as cluster-apps
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: flux/clusters/clustername/apps
  prune: true
  dependsOn:
    - name: cluster-infrastructure
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-values
---
# Include flux/clusters/clustername/resources as cluster-resources
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-resources
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: flux/clusters/clustername/resources
  prune: true
  dependsOn:
    - name: cluster-infrastructure
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-values