---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 12h
  ref:
    semver: ">=0.28.0"
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 12h
  chartRef:
    kind: OCIRepository
    name: flux-operator
    namespace: flux-system
  install:
    createNamespace: true
