---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Base resources that every cluster needs
resources:
  - flux-operator.yaml
  - flux-instance.yaml
  - cluster-config.yaml
  - cluster-values.yaml
