---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: "4.13.x"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: nginx