---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-operator
  namespace: mariadb-operator
spec:
  values:
    crds:
      enabled: true
    currentNamespaceOnly: true
