---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: teamspeak
  namespace: teamspeak
spec:
  interval: 12h
  url: "https://syntax3rror404.github.io/helm-charts/charts"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teamspeak
  namespace: teamspeak
spec:
  interval: 30m
  chart:
    spec:
      chart: teamspeak
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: teamspeak
        namespace: teamspeak
      interval: 12h