---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  values:
    authentik:
      secret_key: "${authentik_secret_key}"
      postgresql:
        password: "${authentik_postgresql_password}"
      email:
        host: "${system_mail_server}"
        port: "${system_mail_port}"
        username: "${system_mail_account}"
        password: "${system_mail_token}"
        use_ssl: true
        timeout: 30
        from: "${authentik_email}"
    postgresql:
      enabled: true
      auth:
        password: "${authentik_postgresql_password}"
      primary:
        persistence:
          enabled: true
          storageClass: longhorn
    redis:
      enabled: true
      master:
        persistence:
          storageClass: longhorn
          enabled: false
