---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  values:
    persistence:
      enabled: true
      create: true
      mount: true
      size: 10Gi
      storageClass: longhorn-prod

    gitea:
      config:
        database:
          DB_TYPE: mysql
          HOST: mariadb-prod-internal.mariadb-prod.svc
          NAME: forgejo
          USER: forgejo
          PASSWD: "${forgejo_mariadb_password}"
        server:
          ROOT_URL: https://git.${cilium_domain}
          SSH_DOMAIN: git.${cilium_domain}
          DOMAIN: git.${cilium_domain}

    httpRoute:
      enabled: true
      parentRefs:
        - name: envoy-gateway-external
          namespace: envoy-gateway-system
      hostnames:
        - git.${nginx_domain}