---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  values:
    persistence:
      enabled: true
      create: true
      mount: true
      size: 10Gi
      storageClass: longhorn-prod

    gitea:
      config:
        database:
          DB_TYPE: mysql
          HOST: mariadb-prod-internal.mariadb-prod.svc
          NAME: forgejo
          USER: forgejo
          PASSWD: "${forgejo_mariadb_password}"
        server:
          ROOT_URL: https://git.${cilium_domain}
          SSH_DOMAIN: git.${cilium_domain}
          DOMAIN: git.${cilium_domain}

    httpRoute:
      enabled: false
      parentRefs:
        - name: envoy-gateway-external
          namespace: envoy-gateway-system
      hostnames:
        - git.${nginx_domain}

      containerSecurityContext: 
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        # Add the SYS_CHROOT capability for root and rootless images if you intend to
        # run pods on nodes that use the container runtime cri-o. Otherwise, you will
        # get an error message from the SSH server that it is not possible to read from
        # the repository.
        # https://gitea.com/gitea/helm-chart/issues/161
          add:
            - SYS_CHROOT
        privileged: false
        readOnlyRootFilesystem: true
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000