---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  values:
    persistence:
      enabled: true
      create: true
      mount: true
      size: 10Gi
      storageClass: longhorn-prod

    ingress:
      enabled: true
      className: cilium

      annotations:
        ingress.cilium.io/loadbalancer-mode: shared
        ingress.cilium.io/websocket: enabled
      hosts:
        - host: git.${cilium_domain}
          paths:
            - path: /
              pathType: Prefix
              port: http
      tls:
        - hosts:
            - git.${cilium_domain}

    gitea:
      config:
        database:
          DB_TYPE: mysql
          HOST: mariadb-prod-internal.mariadb-prod.svc
          NAME: forgejo
          USER: forgejo
          PASSWD: "${forgejo_mariadb_password}"