---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  values:
    persistence:
      enabled: true
      create: true
      mount: true
      size: 10Gi
      storageClass: longhorn-prod

    gitea:
      config:
        database:
          DB_TYPE: mysql
          HOST: mariadb-prod-internal.mariadb-prod.svc
          NAME: forgejo
          USER: forgejo
          PASSWD: "${forgejo_mariadb_password}"
        server:
          ROOT_URL: git.${cilium_domain}