---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  values:
    deployment:
      replicaCount: 3

    persistence:
      meta:
        storageClass: "longhorn-prod"
        size: 500Mi
      data:
        storageClass: "longhorn-prod"
        size: 5Gi
