---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  values:
    updateStrategy:
      type: Recreate

    expose:
      type: route
      tls:
        enabled: false
      route:
        parentRefs:
          - name: envoy-gateway-internal
            namespace: envoy-gateway-system
        hosts:
          - "harbor.${internal_domain}"

    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: "longhorn-staging"
          size: 50Gi
        redis:
          storageClass: "longhorn-staging"
          size: 1Gi
        jobservice:
          jobLog:
            storageClass: "longhorn-staging"
            size: 1Gi
        trivy:
          storageClass: "longhorn-staging"
          size: 1Gi

    core:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
    portal:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi
    jobservice:
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          memory: 128Mi
    registry:
      resources:
        requests:
          cpu: 20m
          memory: 64Mi
        limits:
          memory: 128Mi
    redis:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          memory: 64Mi
    trivy:
      resources:
        requests:
          cpu: 100m
          memory: 32Mi
        limits:
          memory: 256Mi

    database:
      type: external
      external:
        host: "pgsql-prod-rw.pgsql-prod.svc"
        port: "5432"
        existingSecret: ""
        coreDatabase: "harbor"
        username: "harbor"
        password: "password"
