---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor
spec:
  values:

    expose:
      type: route
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: "harbor-ingress"
      route:
        parentRefs:
          - name: envoy-gateway-internal
            namespace: envoy-gateway-system
        hosts:
          - "harbor.${cilium_domain}"

    persistence:
      persistentVolumeClaim:
        registry:
          storageClass: "longhorn-staging"
          size: 50Gi
        redis:
          storageClass: "longhorn-staging"
          size: 1Gi
        jobservice:
          jobLog:
            storageClass: "longhorn-staging"
            size: 1Gi
        trivy:
          storageClass: "longhorn-staging"
          size: 1Gi

    database:
      type: external
      external:
        host: "pgsql-prod-rw.pgsql-prod.svc"
        port: "5432"
        existingSecret: ""
        coreDatabase: "harbor"
        username: "harbor"
        password: "password"
