---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: minecraft
spec:
  values:

    image:
      tag: "25.0.2_10-jre-alpine-3.23"

    service:
      port: 25565
      labels:
        lb.cilium.io/pool: general

    persistence:
      enabled: true
      storageClass: "longhorn-staging"

    neoforge:
      enabled: true

    minecraft:
      eulaAccepted: true
      jvmOpts: "-Xms1G -Xmx4G -XX:+UseCompactObjectHeaders -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=10 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=16M -XX:G1ReservePercent=10 -XX:InitiatingHeapOccupancyPercent=15 -XX:+UseStringDeduplication -XX:+OptimizeStringConcat"
      serverProperties:
        levelName: "mog-world"
        whiteList: "false"