---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  values:
    vmsingle:
      spec:
        retentionPeriod: "2" # in months
        storage:
          storageClassName: "${default_storage_class}"
          resources:
            requests:
              storage: 50Gi

    victoria-metrics-operator:
      operator:
        disable_prometheus_converter: true

    grafana:
      deploymentStrategy:
        type: Recreate
        rollingUpdate: null
      persistence:
        enabled: true
        storageClassName: "${default_storage_class}"
        size: 5Gi
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      route:
        main:
          enabled: true
          hostnames:
            - monitoring.${cilium_domain}
          parentRefs:
            - name: envoy-gateway-internal
              namespace: envoy-gateway-system
