---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  values:
    nextcloud:
      host: nextcloud.${nginx_domain}
      username: admin
      password: ${nextcloud_admin_password}

      configs:
        custom-overwrite.config.php: |-
          <?php
          $CONFIG = array (
            'overwrite.cli.url' => 'https://nextcloud.nextcloud.svc.cluster.local',
            'overwriteprotocol' => 'https',
          );

        custom.config.php: |
          <?php
            $CONFIG = array(
              'check_data_directory_permissions' => false, # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/
              'allow_local_remote_servers' => true,
            );

        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.0.0.0/8',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );

        domains.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_domains' =>
              array (
              0 => '192.168.35.*',
              1 => 'nextcloud.tokamak.labza',
              2 => 'nextcloud.menofgaming.de',
              3 => 'rancher.tokamak.labza',
              4 => 'nextcloud.tokamak.labza',
              )
          );

        logging.config.php: |-
          <?php
          $CONFIG = array (
            'log_type' => 'file',
            'logfile' => 'nextcloud.log',
            'loglevel' => 2,
            'logdateformat' => 'F d, Y H:i:s'
            );

    persistence:
      enabled: true
      size: 500Gi
      storageClass: "longhorn-prod"

    image:
      flavor: fpm

    cronjob:
      enabled: true
      useCronJobInsteadOfCrond: true
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

    nginx:
      enabled: true
      image:
        repository: nginxinc/nginx-unprivileged
        tag: alpine
        pullPolicy: IfNotPresent
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        runAsNonRoot: true
        readOnlyRootFilesystem: false

    #externalDatabase:
    #  enabled: true
    #  type: mysql
    #  host: mariadb-prod-internal.mariadb-prod.svc
    #  user: nextcloud
    #  password: "${nextcloud_mariadb_password}"
    #  database: nextcloud

    externalDatabase:
      enabled: true
      type: mysql
      host: nextcloud-mariadb.svc
      user: nextcloud
      password: "${nextcloud_mariadb_password}"
      database: nextcloud

    mariadb:
      enabled: true
      primary:
        livenessProbe:
          enabled: false
        readinessProbe:
          enabled: false
        persistence:
          enabled: true
          storageClass: "longhorn-prod"
      auth:
        database: nextcloud
        username: nextcloud
        password: "${nextcloud_mariadb_password}"
        rootPassword: "${nextcloud_mariadb_root_password}"
        existingSecret: ""
