---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbao
  namespace: openbao
spec:
  values:
    server:
      dataStorage:
        storageClass: longhorn-staging
      gateway:
        # Configures a TLSRoute for the OpenBao server. This can be enabled independently of the ingress configuration to allow for side-by-side scenarios for migration.
        httpRoute:
          enabled: true
          labels: {}
          # traffic: external
          annotations: {}
          # external-dns.alpha.kubernetes.io/hostname: chart-example.local

          hosts:
            - openbao.${cilium_domain}

          # Allows overriding the TLSRoutes apiVersion in case a different version of Gateway API is installed on the cluster.
          apiVersion: gateway.networking.k8s.io/v1 

          # When HA mode is enabled and K8s service registration is being used,
          # configure the ingress to point to the OpenBao active service.
          activeService: true

          parentRefs:
            - group: gateway.networking.k8s.io
              kind: Gateway
              name: envoy-gateway-internal
              namespace: envoy-gateway-system

      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
