---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  values:
    hostname: rancher.${cilium_domain}
    ingress:
      enabled: true
      extraAnnotations:
        ingress.cilium.io/loadbalancer-mode: shared
        ingress.cilium.io/websocket: enabled
      ingressClassName: cilium
