---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    hostname: rancher.${cilium_domain}
    ingress:
      enabled: true
      extraAnnotations:
        ingress.cilium.io/loadbalancer-mode: shared
        ingress.cilium.io/websocket: enabled
      ingressClassName: cilium
