---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snipe-it
  namespace: snipeit
spec:
  values:
    # MariaDB
    mariadbOperator:
      enabled: true
      database: snipeit
      username: snipeit
      password: "${snipeit_mariadb_password}"
      useExisting:
        enabled: true
        namespace: mariadb-prod
        mariaDbRef: mariadb-prod

    # snipeit config
    snipeit:
      entrypointOverride:
        enabled: false
      config:
        url: "https://wms.${nginx_domain}"
        timezone: Europe/Berlin
        locale: en
      persistence:
        size: 50Gi
        storageClass: longhorn-prod
