---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      dataStorage:
        size: 10Gi
        storageClass: longhorn-staging
      image:
        tag: 1.20.1
      ingress:
        enabled: true
        ingressClassName: cilium
        annotations:
          cert-manager.io/cluster-issuer: labza-ca
          ingress.cilium.io/loadbalancer-mode: shared
          ingress.cilium.io/websocket: enabled
          cert-manager.io/private-key-algorithm: ECDSA
          cert-manager.io/private-key-size: "256"
        hosts:
          - host: vault.${cilium_domain}
            paths: []
        tls:
          - hosts:
              - vault.${cilium_domain}
            secretName: vault-ingress-cert

      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
