---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: "${weave_gitops_password_hash}"
    ingress:
      enabled: true
      className: cilium
      annotations:
        cert-manager.io/cluster-issuer: labza-ca
        ingress.cilium.io/loadbalancer-mode: shared
        ingress.cilium.io/websocket: enabled
      hosts:
        - host: gitops.${cilium_domain}
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: weave-gitops-tls
          hosts:
            - gitops.${cilium_domain}