---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snipeit
  namespace: snipeit
spec:
  interval: 12h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    semver: ">=2.0.0 <3.0.0"
  url: oci://ghcr.io/syntax3rror404/helm-charts/snipeit
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snipe-it
  namespace: snipeit
spec:
  interval: 1h
  maxHistory: 3
  chartRef:
    kind: OCIRepository
    name: snipeit
    namespace: snipeit