---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 10m
  ref:
    tag: 4.0.36
    digest: sha256:7962f594c278045646e5d0c51498d4981a295ecda8e340c3f106d63505bdf828
  url: oci://ghcr.io/weaveworks/charts/weave-gitops
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: weave-gitops
    namespace: weave-gitops
  values:
    adminUser:
      create: true
      username: admin
      passwordHash: "changeme"
    ingress:
      enabled: false  # We manage ingress separately
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi