---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  # Merge production-specific configuration
  - path: config.yaml
    target:
      kind: HelmRelease
      name: weave-gitops
      namespace: weave-gitops
  
  # # Patch ingress for prod environment with additional annotations
  # - patch: |
  #     - op: replace
  #       path: /spec/rules/0/host
  #       value: gitops.prod-cluster.local
  #     - op: add
  #       path: /metadata/annotations
  #       value:
  #         ingress.cilium.io/loadbalancer-mode: shared
  #         ingress.cilium.io/websocket: enabled
  #   target:
  #     kind: Ingress
  #     name: weave-gitops-cilium
  #     namespace: weave-gitops