---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  values:
    server:
      dataStorage:
        enabled: true
        size: 10Gi
        storageClass: changeme
        accessMode: ReadWriteOnce

      # Comment out to allow instances on one node
      affinity:
        {}
        # podAntiAffinity:
        #   requiredDuringSchedulingIgnoredDuringExecution:
        #     - labelSelector:
        #         matchLabels:
        #           app.kubernetes.io/name: vault
        #           app.kubernetes.io/instance: vault
        #           component: server
        #       topologyKey: kubernetes.io/hostname

      ingress:
        enabled: false
        ingressClassName: cilium
        labels:
          {}
          # traffic: external
        pathType: Prefix
        activeService: true
        annotations:
          cert-manager.io/cluster-issuer: changeme
        hosts:
          - host: vault.example.com
            paths: []
        tls:
          - hosts:
              - vault.example.com
            secretName: vault-ingress-cert
      ha:
        apiAddr: null
        disruptionBudget:
          enabled: false
          maxUnavailable: null
        enabled: true
        replicas: 3
        raft:
          enabled: true
          setNodeId: true
          config: |
            ui = true
            listener "tcp" {
              tls_disable = 1
              address = "[::]:8200"
              cluster_address = "[::]:8201"
            }
            storage "raft" {
              path = "/vault/data"
              retry_join {
                leader_api_addr = "http://vault-0.vault-internal.vault.svc:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-1.vault-internal.vault.svc:8200"
              }
              retry_join {
                leader_api_addr = "http://vault-2.vault-internal.vault.svc:8200"
              }
            }
            service_registration "kubernetes" {}
