---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  # Merge production-specific configuration
  - path: config.yaml
    target:
      kind: HelmRelease
      name: vault
      namespace: vault
