---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-test
  namespace: mariadb-test
spec:
  values:
    primary:
      persistence:
        storageClass: longhorn
        size: 20Gi
      service:
        type: ClusterIP
        ports:
          mysql: 3306
    commonLabels:
      app: mariadb-test
      environment: development
    auth:
      rootPassword: "test"
      database: "app_dev_1"
      username: "app_user_1"
      password: "test"
    
    # Performance-spezifische Konfiguration für dev-1
    resources:
      limits:
        memory: 2Gi
        cpu: 1000m
      requests:
        memory: 1Gi
        cpu: 500m
    
    # MariaDB-spezifische Konfiguration
    configuration: |-
      [mysqld]
      max_connections=200
      innodb_buffer_pool_size=1G
      server-id=1