---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 1h
  timeout: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  verify:
    provider: cosign
  ref:
    tag: 6.x.x
  url: oci://ghcr.io/stefanprodan/charts/podinfo
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: podinfo
    namespace: podinfo
  values:
    # Base values
    replicaCount: 1
    service:
      enabled: true
      type: ClusterIP
    ingress:
      enabled: false
    persistence:
      enabled: false
      storageClass: ""