---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: flux-system
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "flux-tokamak"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "flux-vault-token"
          key: "token"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cluster-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # weave-gitops
        weave_gitops_password_hash: "{{ .weave_gitops_password_hash }}"
        # authentik
        authentik_postgresql_password: "{{ .authentik_postgresql_password }}"
        authentik_secret_key: "{{ .authentik_secret key }}"
  data:
  - secretKey: weave_gitops_password_hash
    remoteRef:
      key: flux-tokamak/weave-gitops
      property: password_hash
  - secretKey: authentik_postgresql_password
    remoteRef:
      key: flux-tokamak/authentik
      property: postgresql_password
  - secretKey: authentik_secret_key
    remoteRef:
      key: flux-tokamak/authentik
      property: secret_key