#   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #
# VAULT TOKAMAK CLUSTER https://vault.tokamak.labza/ui/vault/secrets/flux-tokamak/kv/list VAULT TOKAMAK CLUSTER #
#   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #   #
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: flux-system
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "flux-tokamak"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "flux-vault-token"
          key: "token"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  refreshPolicy: Periodic
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: cluster-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # weave-gitops
        weave_gitops_password_hash: "{{ .weave_gitops_password_hash }}"

        # authentik
        authentik_postgresql_password: "{{ .authentik_postgresql_password }}"
        authentik_secret_key: "{{ .authentik_secret_key }}"
        authentik_email: "{{ .authentik_email }}"

        # system-mail
        system_mail_account: "{{ .system_mail_account }}"
        system_mail_port: "{{ .system_mail_port }}"
        system_mail_server: "{{ .system_mail_server }}"
        system_mail_token: "{{ .system_mail_token }}"

        # nextcloud
        nextcloud_admin_password: "{{ .nextcloud_admin_password }}"
        nextcloud_mariadb_password: "{{ .nextcloud_mariadb_password }}"
        nextcloud_mariadb_root_password: "{{ .nextcloud_mariadb_root_password }}"

        # snipe-it
        snipeit_mariadb_root_password: "{{ .snipeit_mariadb_root_password }}"
        snipeit_mariadb_password: "{{ .snipeit_mariadb_password }}"

        # mariadb-prod
        mariadb_prod_root_password: "{{ .mariadb_prod_root_password }}"

        # teamspeak
        teamspeak_mariadb_password: "{{ .teamspeak_mariadb_password }}"
        teamspeak_mariadb_root_password: "{{ .teamspeak_mariadb_root_password }}"

  data:
    # weave-gitops https://vault.tokamak.labza/ui/vault/secrets/flux-tokamak/kv/weave-gitops
    - secretKey: weave_gitops_password_hash
      remoteRef:
        key: flux-tokamak/weave-gitops
        property: password_hash

    # authentik https://vault.tokamak.labza/ui/vault/secrets/flux-tokamak/kv/authentik
    - secretKey: authentik_postgresql_password
      remoteRef:
        key: flux-tokamak/authentik
        property: postgresql_password
    - secretKey: authentik_secret_key
      remoteRef:
        key: flux-tokamak/authentik
        property: secret_key
    - secretKey: authentik_email
      remoteRef:
        key: flux-tokamak/authentik
        property: email

    # system-mail https://vault.tokamak.labza/ui/vault/secrets/flux-tokamak/kv/system-mail
    - secretKey: system_mail_account
      remoteRef:
        key: flux-tokamak/system-mail
        property: account
    - secretKey: system_mail_port
      remoteRef:
        key: flux-tokamak/system-mail
        property: port
    - secretKey: system_mail_server
      remoteRef:
        key: flux-tokamak/system-mail
        property: server
    - secretKey: system_mail_token
      remoteRef:
        key: flux-tokamak/system-mail
        property: token

    # nextcloud https://vault.tokamak.labza/ui/vault/secrets/flux-tokamak/kv/nextcloud
    - secretKey: nextcloud_admin_password
      remoteRef:
        key: flux-tokamak/nextcloud
        property: adminPW
    - secretKey: nextcloud_mariadb_password
      remoteRef:
        key: flux-tokamak/nextcloud
        property: mariadbPW
    - secretKey: nextcloud_mariadb_root_password
      remoteRef:
        key: flux-tokamak/nextcloud
        property: mariadbRootPW

    # snipe-it https://vault.tokamak.labza/ui/vault/secrets/flux-tokamak/kv/snipeit
    - secretKey: snipeit_mariadb_root_password
      remoteRef:
        key: flux-tokamak/snipeit
        property: mariadbRootPW
    - secretKey: snipeit_mariadb_password
      remoteRef:
        key: flux-tokamak/snipeit
        property: mariadbPW

    # mariadb-prod https://vault.tokamak.labza/ui/vault/secrets/flux-tokamak/kv/mariadb-prod
    - secretKey: mariadb_prod_root_password
      remoteRef:
        key: flux-tokamak/mariadb-prod
        property: mariadbRootPW

    # teamspeak https://vault.tokamak.labza/ui/vault/secrets/flux-tokamak/kv/teamspeak
    - secretKey: teamspeak_mariadb_password
      remoteRef:
        key: flux-tokamak/teamspeak
        property: mariadbPW
    - secretKey: teamspeak_mariadb_root_password
      remoteRef:
        key: flux-tokamak/teamspeak
        property: mariadbRootPW
