---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m
  ref:
    tag: 0.22.0
    digest: sha256:8f0cf55a0f216c30fc5c3da65c25f0061382c03caae8794b5d37882a3b1d2605
  url: oci://ghcr.io/controlplaneio-fluxcd/charts/flux-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: flux-operator
    namespace: flux-system
  install:
    createNamespace: true