---
# Tokamak-specific FluxInstance
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    multitenant: false
    networkPolicy: true
    domain: "cluster.local"
  sync:
    kind: GitRepository
    url: "https://github.com/Syntax3rror404/infra.git"
    ref: "refs/heads/main"
    path: "flux/clusters/tokamak"
    pullSecret: "flux-system"
    interval: "1m0s"