---
# flux/clusters/tokamak/kustomization.yaml (Updated)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base cluster configuration
resources:
  - ../base
  - cluster-values.yaml

# Apply cluster-specific values
postBuild:
  substituteFrom:
    - kind: ConfigMap
      name: cluster-values