---
# flux/clusters/tokamak/kustomization.yaml (Updated)
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base cluster configuration
resources:
  - ../base
  - cluster-values.yaml

# Cluster-specific patches
patches:
  # Update flux-instance path with cluster name
  - patch: |
      - op: replace
        path: /spec/sync/path
        value: "flux/clusters/tokamak"
    target:
      kind: FluxInstance
      name: flux
      namespace: flux-system

# Apply cluster-specific values
postBuild:
  substituteFrom:
    - kind: ConfigMap
      name: cluster-values