---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

# Override the base cluster-values with cluster-specific values
patches:
  - path: cluster-values.yaml
    target:
      kind: ConfigMap
      name: cluster-values
      namespace: flux-system

# Apply cluster-specific values
postBuild:
  substituteFrom:
    - kind: ConfigMap
      name: cluster-values