---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include base cluster configuration
resources:
  - ../base

# Override the base cluster-values with tokamak-specific values
patches:
  - path: cluster-values.yaml
    target:
      kind: ConfigMap
      name: cluster-values
      namespace: flux-system
  
  # Patch cluster-apps to use correct tokamak path
  - patch: |
      - op: replace
        path: /spec/path
        value: flux/clusters/tokamak/apps
    target:
      kind: Kustomization
      name: cluster-apps
      namespace: flux-system
  
  # Patch cluster-resources to use correct tokamak path
  - patch: |
      - op: replace
        path: /spec/path
        value: flux/clusters/tokamak/resources
    target:
      kind: Kustomization
      name: cluster-resources
      namespace: flux-system
  
  # Patch flux-instance to use correct tokamak path
  - patch: |
      - op: replace
        path: /spec/sync/path
        value: flux/clusters/tokamak
    target:
      kind: FluxInstance
      name: flux
      namespace: flux-system

# Apply cluster-specific values
postBuild:
  substituteFrom:
    - kind: ConfigMap
      name: cluster-values