---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../apps/mariadb/base

# Transform resources for mariadb-prod
patches:
  # Update namespace
  - patch: |
      - op: replace
        path: /metadata/name
        value: mariadb-prod
    target:
      kind: Namespace
      name: mariadb

  # Update OCIRepository
  - patch: |
      - op: replace
        path: /metadata/name
        value: mariadb-prod
      - op: replace
        path: /metadata/namespace
        value: mariadb-prod
    target:
      kind: OCIRepository
      name: mariadb

  # Update HelmRelease
  - patch: |
      - op: replace
        path: /metadata/name
        value: mariadb-prod
      - op: replace
        path: /metadata/namespace
        value: mariadb-prod
      - op: replace
        path: /spec/chartRef/name
        value: mariadb-prod
      - op: replace
        path: /spec/chartRef/namespace
        value: mariadb-prod
    target:
      kind: HelmRelease
      name: mariadb

  # Apply cluster-specific values
  - path: mariadb-prod-values.yaml
    target:
      kind: HelmRelease
      name: mariadb-prod
      namespace: mariadb-prod
