---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mariadb-prod
  namespace: mariadb-prod
spec:
  values:
    primary:
      persistence:
        storageClass: longhorn-prod
      service:
        type: LoadBalancer
    commonLabels:
      ciliuml2: pool
    auth:
      rootPassword: "${mariadb_prod_root_password}"
