# helm --namespace=kube-system install coredns coredns/coredns -f config.yaml
---
# Rplica count for External Secret
replicaCount: 2
# Tolerations to allow scheduling on control-plane nodes
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

# Preferred scheduling on control-plane nodes
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists

    # Fallback to any node if no control-plane nodes are available
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        # First Option: Control Plane Nodes
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
        # Second Option: Master Nodes
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: Exists
        # Third Option: Any Node
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists

  # Pod Anti-Affinity to avoid scheduling on the same node
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        podAffinityTerm:
          labelSelector:
            matchLabels:
              k8s-app: kube-dns
          topologyKey: kubernetes.io/hostname

k8sAppLabelOverride: "kube-dns"
service:
  name: kube-dns

servers:
  - zones:
      - zone: .
        scheme: dns://
        use_tcp: true
    port: 53
    plugins:
      - name: errors
      # Serves a /health endpoint on :8080, required for livenessProbe
      - name: health
        configBlock: |-
          lameduck 10s
      # Serves a /ready endpoint on :8181, required for readinessProbe
      - name: ready
      # Required to query kubernetes API for data
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
          ttl 30
      # Serves a /metrics endpoint on :9153, required for serviceMonitor
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: forward
        parameters: . /etc/resolv.conf
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
