---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml

patches:
  - path: config.yaml
    target:
      kind: HelmRelease
      name: coredns
      namespace: kube-system
